name: 'Build & Release'

on:
  workflow_dispatch:
  push:
    branches:
      - stable
      - develop
    tags:
      - "release/*"
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-windows, x86_64-linux, x86_64-macos, aarch64-macos]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2.1.1
        with:
          version: 0.11.0-dev.3971+6bc9c4f71

      - name: Dependencies
        run: |
          sudo apt-get install -y xorg-dev mingw-w64

      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      #   with:
      #     ## limits ssh access and adds the ssh public keys of the listed GitHub users
      #     limit-access-to-users: recursiveGecko

      - name: Build (Windows)
        if: contains(matrix.target, 'windows')
        run: |
          zig build -Dtarget=${{matrix.target}} -Dfilename-suffix=${{matrix.target}}

      - name: Build (macOS)
        if: contains(matrix.target, 'macos')
        run: |
          zig build -Dtarget=${{matrix.target}} -Dfilename-suffix=${{matrix.target}} -Doptimize=ReleaseSafe --sysroot lib/MacOSX11.3.sdk/
          python3 ./scripts/generate-macos-app.py --plist data/Info.plist --icon data/icon.png --exe zig-out/bin/mv-widgets-${{matrix.target}} --out zig-out/mv-widgets-${{matrix.target}}.tar

      - name: Build (Linux)
        if: contains(matrix.target, 'linux')
        run: |
          zig build -Dfilename-suffix=${{matrix.target}} -Dcpu=x86_64 -Doptimize=ReleaseSafe

      - name: Artifacts (Linux/Windows)
        uses: actions/upload-artifact@v3
        if: ${{ !contains(matrix.target, 'macos') }}
        with:
          name: mv-widgets-${{ matrix.target }}
          path: |
            zig-out/bin
            !zig-out/bin/*.pdb

      - name: Artifacts (MacOS)
        uses: actions/upload-artifact@v3
        with:
          name: mv-widgets-${{ matrix.target }}
          path: |
            zig-out/mv-widgets-${{matrix.target}}.tar

  release:
    needs: [build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            artifacts/*/*
          draft: true
          fail_on_unmatched_files: true
