name: 'Build & Release'

on:
  workflow_dispatch:
  push:
    branches:
      - stable
      - develop
    tags:
      - "release/*"
  pull_request:

jobs:
  build-release:
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            target: aarch64-macos-none
          - os: macos-latest
            target: x86_64-macos-none

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2.1.1
        with:
          version: 0.11.0-dev.3971+6bc9c4f71

      - name: Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y xorg-dev

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: |
          zig build

      - name: Build (macOS)
        if: runner.os == 'macOS'
        run: |
          zig build -Dtarget=${{matrix.target}} -Doptimize=ReleaseSafe

      - name: Build (Linux)
        if: runner.os == 'Linux'
        run: |
          zig build -Doptimize=ReleaseSafe

      - uses: actions/upload-artifact@v3
        with:
          name: mv-widgets-${{ matrix.os }}-${{ matrix.target }}
          path: zig-out

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            zig-out/bin/mv-widgets-x86_64-windows.exe
          draft: true
