name: 'Build & Release'

on:
  workflow_dispatch:
  push:
    branches:
      - stable
      - develop
    tags:
      - "release/*"
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-windows, x86_64-linux, x86_64-macos, aarch64-macos]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2.1.1
        with:
          version: 0.11.0-dev.3971+6bc9c4f71

      - name: Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y xorg-dev

      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      #   with:
      #     ## limits ssh access and adds the ssh public keys of the listed GitHub users
      #     limit-access-to-users: recursiveGecko

      - name: Build (Windows)
        if: contains(matrix.target, 'windows')
        run: |
          zig build -Dtarget=${{matrix.target}}

      - name: Build (macOS)
        if: contains(matrix.target, 'macos')
        run: |
          zig build -Dtarget=${{matrix.target}} -Doptimize=ReleaseSafe --sysroot lib/MacOSX11.3.sdk/

      - name: Build (Linux)
        if: contains(matrix.target, 'linux')
        run: |
          zig build -Dcpu=x86_64 -Doptimize=ReleaseSafe

      - uses: actions/upload-artifact@v3
        with:
          name: mv-widgets-${{ matrix.target }}
          path: zig-out/bin

  release:
    needs: [build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            artifacts/*
          draft: true
